version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - gatsby-theme-brikl-store-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - gatsby-theme-brikl-store-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: gatsby-theme-brikl-store-{{ checksum "package.json" }}
  deploy:
    steps:
      - attach_workspace:
        at: ~/repo
      - run:
        name: Authenticate with registry
        command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
        name: Publish package
        command: npm publish
workflows:
  version: 2
  build_release:
    jobs:
      - build
      - release:
          filters:
            branches:
              only: master
          requires:
            - build
