version: 2
jobs:
  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - gatsby-theme-brikl-store-{{ checksum "package.json" }}
      - run: Navigation to theme directory
        command: cd ~/repo/theme
      - run:
        name: Authenticate with registry
        command: echo "//packagecloud.io/armando/node-test-package/npm/:_authToken=$npm_TOKEN" > ~/repo/theme/.npmrc
      - run:
        name: Publish package
        command: npm publish
workflows:
  version: 2
  build_release:
    jobs:
      - build
      - release:
          filters:
            branches:
              only: master
          requires:
            - build
